AddedSevereSlug
equinor/neqsim pull request #560
Opened 2022-10-31 12:29 UTC by Sviatose

AddedSevereSlug

2022-10-31 12:30 UTC, Sviatose reviewed
Added Severe Slug

2022-11-01 12:46 UTC, Sviatose commented
Added the new tests. Now it references on the same stream object.

2022-11-03 07:14 UTC, EvenSol requested changes
Very nice work :-)
Can you update so that it uses stream properties of input stream in calculations?

2022-11-03 16:05 UTC, EvenSol approved these changes

2022-11-03 16:09 UTC, merged